project:
  type: book
  output-dir: docs

book:
  title: "The openair book"
  subtitle: "A Guide to the Analysis of Air Pollution Data"
  author: 
  - David C Carslaw
  - Jack Davison
  reader-mode: true
  
  favicon: assets/media/favicon.png
  site-url: https://openair-project.github.io/book/
  repo-url: https://github.com/openair-project/book/
  repo-branch: main
  repo-actions: [edit, issue]
  sharing: [twitter, facebook, linkedin]
  date: today
  date-format: long

  sidebar: 
    search: true
    logo: assets/media/plume.png
    collapse-level: 1

  page-footer:
    left: |
      The openair book is part of the <a href='https://github.com/openair-project'>openair project</a>
    right: |
      This work is licensed under a [CC0 1.0 Universal License](https://creativecommons.org/publicdomain/zero/1.0/).

  chapters:
    - index.qmd
    - sections/intro/intro.qmd
    - sections/intro/openair-package.qmd
    
    - part: "Data Access"
      chapters:
        - sections/data-access/UK-air-quality-data.qmd
        - sections/data-access/access-met-data.qmd
        
    - part: "Directional Analysis"
      chapters:
        - sections/directional-analysis/wind-roses.qmd
        - sections/directional-analysis/polar-freq.qmd
        - sections/directional-analysis/percentile-roses.qmd
        - sections/directional-analysis/polar-plots.qmd
        - sections/directional-analysis/polar-annulus.qmd
        - sections/directional-analysis/trajectory-analysis.qmd
        
    - part: "Time Series and Trends"
      chapters:
        - sections/trend-analysis/time-plot.qmd
        - sections/trend-analysis/time-variation.qmd
        - sections/trend-analysis/calendar-plot.qmd
        - sections/trend-analysis/time-proportion.qmd
        - sections/trend-analysis/theil-sen.qmd
        - sections/trend-analysis/smooth-trend.qmd
        - sections/trend-analysis/run-regression.qmd
        - sections/trend-analysis/trend-level.qmd
        - sections/trend-analysis/ts-smoothing.qmd
        - sections/trend-analysis/ts-filtering.qmd
        
    - part: "Model Evaluation"
      chapters:
        - sections/model-evaluation/mod-stats.qmd
        - sections/model-evaluation/taylor-diagram.qmd
        - sections/model-evaluation/conditional-quantiles.qmd
        
    - part: "Interactive Maps"
      chapters:
        - sections/maps/maps-overview.qmd
        - sections/maps/maps-network.qmd
        - sections/maps/maps-polar.qmd
        - sections/maps/maps-traj.qmd
        
    - part: "Utility functions"
      chapters:
        - sections/utilities/utility-functions.qmd
        - sections/utilities/scatter-plot.qmd
        
    - sections/references.qmd
    
  appendices:
   - sections/appendices/appendix-annotate.qmd
   - sections/appendices/appendix-colours.qmd
   - sections/appendices/appendix-hysplit.qmd
   - sections/appendices/appendix-trends.qmd
   - sections/appendices/appendix-gethelp.qmd
   - v3.qmd

bibliography: 
 - assets/bib/DCC-refs.bib
 - assets/bib/packages.bib

execute:
  warning: false
  message: false
  echo: true
  error: false
  eval: true
  prompt: false
  freeze: auto
  cache: true

format:
  html:
    theme: 
      - lumen
      - assets/style/openair.scss
    mainfont: "Nunito Sans"
    monofont: "JetBrains Mono"
    highlight-style: a11y
    code-link: true
    code-copy: true
    fig-align: center
    author-meta: "David Carslaw and Jack Davison"
    callout-appearance: simple
    html-table-processing: none
    citation-location: margin
    link-external-newwindow: true
    lightbox: true

editor: source
editor_options: 
  chunk_output_type: console
